# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US"
title: "Ravi Shankar"
title_separator: "-"
subtitle: "Learning and Sharing"
name: "Ravi Shankar"
description: "Exploring iOS Development, SwiftUI, and Apple Platforms"
url: "https://rshankras.github.io"
baseurl: ""
repository: "rshankras/rshankras.github.io"
masthead_title: "App Development Journey"
email: ravi@rshankar.com
twitter_username: rshankra
github_username: rshankras
minimal_mistakes_skin: "default"
search: true

# Add custom CSS
head_scripts:
  - /assets/css/custom.css

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
permalink: /:title/

# Pagination
paginate: 10
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages

# Site Author
author:
  name             : "Ravi Shankar"
  avatar           : "/assets/images/your-photo.jpg"
  bio              : "Apple Platforms Developer"
  location         : "Chennai, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ravi@rshankar.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rshankra"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rshankras"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/sravis"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rshankra"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rshankras"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/sravis"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation
breadcrumbs: true

# Top Navigation
main:
  - title: "Quick-Start Guide"
    url: /quick-start-guide/
  - title: "About"
    url: /about/
  - title: "Sample Posts"
    url: /posts/
  - title: "Sample Collections"
    url: /collection-archive/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/